#!/usr/bin/env python3

import asyncio
import time
import settings
import sys
import os
from pymongo import MongoClient
from threading import Thread


####
# Start script
####
print("==========================================")
print("         Change Stream App                ")
print("Change Stream Events currently monitored: ")
print("Insert, Update, Delete, Replace           ")
print("                                          ")
print("Resume functionality is a separate thread ")
print("==========================================")


####
# Main start function
# Start each individual thread for each event
# Sleep momentarily after starting each thread
####
def main():
    print('Starting Change Stream Listener.\n')

    # Create thread for insert operation
    insert_thread = asyncio.new_event_loop()
    insert_thread.call_soon_threadsafe(insert_change_stream)
    t = Thread(target=start_thread, args=(insert_thread,))
    t.start()
    time.sleep(0.25)

    # Create the update thread
    update_thread = asyncio.new_event_loop()
    update_thread.call_soon_threadsafe(update_change_stream)
    t = Thread(target=start_thread, args=(update_thread,))
    t.start()
    time.sleep(0.25)

    # Create the delete thread
    delete_thread = asyncio.new_event_loop()
    delete_thread.call_soon_threadsafe(delete_change_stream)
    t = Thread(target=start_thread, args=(delete_thread,))
    t.start()
    time.sleep(0.25)

    # Create the replace thread
    replace_thread = asyncio.new_event_loop()
    replace_thread.call_soon_threadsafe(replace_change_stream)
    t = Thread(target=start_thread, args=(replace_thread,))
    t.start()
    time.sleep(0.25)

    # Create the resume example thread
    resume_thread = asyncio.new_event_loop()
    resume_thread.call_soon_threadsafe(resume_change_stream)
    t = Thread(target=start_thread, args=(resume_thread,))
    t.start()
    time.sleep(0.25)


####
# Make sure the thread continues
####
def start_thread(loop):
    asyncio.set_event_loop(loop)
    loop.run_forever()


####
# Insert Change Stream
####
def insert_change_stream():
    print("Insert listener thread started.")
    mongo_client = MongoClient(MONGODB_ATLAS_URL)
    db = mongo_client[DATABASE]
    _collection = db[COLLECTION]

    # Change stream pipeline , add multiple conditions to filter full document
    pipeline = [
        {'$match': {'operationType': 'insert'}}
    ]

    try:
        for document in _collection.watch(pipeline=pipeline, full_document='updateLookup'):
            result = "=== INSERT EVENT ===\n"
            result = result + "Checking superstore data!\n"
            result = result  + document['fullDocument']+ '\n'
            print(result)
    except KeyboardInterrupt:
        keyboard_shutdown()


####
# Update Change Stream
####
def update_change_stream():
    print("Update listener thread started.")    
    mongo_client = MongoClient(MONGODB_ATLAS_URL)
    db = mongo_client[DATABASE]
    _collection = db[COLLECTION]

    # Make sure resume counter does NOT exist as it is being used
    # to trigger the resume operation in another thread
    pipeline = [
        {'$match': {'operationType': 'update'}}
    ]
    try:
        for document in _collection.watch(pipeline=pipeline, full_document='updateLookup'):
            result = "\n=== UPDATE EVENT ===\n"
            print(str(document['fullDocument']))
            result = result + "superstore: " + str(document['fullDocument']) + '\n'
            result = result + str(document['updateDescription']['updatedFields']) + '\n'
            print(result)

    except KeyboardInterrupt:
        keyboard_shutdown()


####
# Delete Change Stream
####
def delete_change_stream():
    print("Delete listener thread started.")
    print("==All delete operations.\n")
    mongo_client = MongoClient(MONGODB_ATLAS_URL)
    db = mongo_client[DATABASE]
    _collection = db[COLLECTION]

    pipeline = [
        {'$match': {'operationType': 'delete'}}
    ]

    try:
        for document in _collection.watch(pipeline=pipeline, full_document='updateLookup'):
            result = "\n=== DELETE EVENT ===\n"
            result = result + "Row Id deleted from collection: " + str(document['ns']['coll']) + "\n"
            result = result + "Row _id: " + str(document['documentKey']['_id']) + "\n"
            print(result)

    except KeyboardInterrupt:
        keyboard_shutdown()


####
# Replace Change Stream
####
def replace_change_stream():
    print("Replace listener thread started.")
    mongo_client = MongoClient(MONGODB_ATLAS_URL)
    db = mongo_client[DATABASE]
    _collection = db[COLLECTION]

    pipeline = [
        {'$match': {'operationType': 'replace'}}
    ]

    try:

        for document in _collection.watch(pipeline=pipeline, full_document='updateLookup'):
            result = "\n=== REPLACE EVENT ===\n"
            result = result + "Did this change occured from MongoDB Compass?\n"
            result = result + str(document) + "\n"
            print(result)

    except KeyboardInterrupt:
        keyboard_shutdown()


####
# Resume capability implemented
####
def resume_change_stream():
    print("Resume listener thread started.")
    mongo_client = MongoClient(MONGODB_ATLAS_URL)
    db = mongo_client[DATABASE]
    _collection = db[COLLECTION]

    pipeline = [
        {'$match': {'operationType': 'update'}},
        {'$match': {'fullDocument.superstore.Country': 'USA'}} 
    ]

    # cursor to watch for specific updates
    cursor = _collection.watch(pipeline=pipeline, full_document='updateLookup')
    # variable to indicate when to close change stream
    resume_counter = 0

    # loop through docs in cursor
    try:
        for document in cursor:
            resume_token = document['_id']
            resume_counter = resume_counter + 1
            # check that the resume counter field has been updated in document
            fulldoc_resume_counter_value = document['fullDocument']['resumeCounter']

            result = "\n=== RESUME EXAMPLE ===\n"
            result = result + "Resume token: " + str(resume_token) + "\n"
            result = result + "Counter value: " + str(fulldoc_resume_counter_value) + "\n"
            print(result)

            # once the resume_counter is greater than specified integer, sleep, close change stream, restart
            if resume_counter > 4:
                print("Resume Counter: " + str(resume_counter))
                print("Simulate failure for 10 seconds...")
                time.sleep(10)
                cursor.close
                print("Resume Change Stream closed.")
                print("Restart Change Stream with resume token: " + str(resume_token))
                # reset the cursor with resume token
                cursor = _collection.watch(pipeline=pipeline,
                                                   full_document='updateLookup', resume_after=resume_token)
                # reset variables
                resume_counter = 0
                continue

    except KeyboardInterrupt:
        keyboard_shutdown()


###
# "Gracefully" consume output via ctrl-c
###
def keyboard_shutdown():
    print('Interrupted\n')
    try:
        sys.exit(0)
    except SystemExit:
        os._exit(0)


####
# Constants loaded from .env file
####
MONGODB_ATLAS_URL = settings.MONGODB_ATLAS_URL
DATABASE = settings.DATABASE
COLLECTION = settings.COLLECTION

####
# Main
####
if __name__ == '__main__':
    main()
